services:
  rofl-relayer:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/rube-de/rofl-relayer:latest
    platform: linux/amd64
    container_name: rofl_relayer
    entrypoint: /bin/sh -c 'uv run python main.py'
    environment:
      # Python configuration
      PYTHONUNBUFFERED: 1  # Disable output buffering for immediate log visibility
      
      # Source chain configuration (Ethereum Sepolia)
      SOURCE_RPC_URL: ${SOURCE_RPC_URL:-}  # Required - Ethereum RPC endpoint
      PING_SENDER_ADDRESS: ${PING_SENDER_ADDRESS:-}  # Required - PingSender contract address
      
      # Target chain configuration (Oasis Sapphire)
      TARGET_NETWORK: ${TARGET_NETWORK:-sapphire-testnet}
      PING_RECEIVER_ADDRESS: ${PING_RECEIVER_ADDRESS:-}  # Required - PingReceiver contract address
      ROFL_ADAPTER_ADDRESS: ${ROFL_ADAPTER_ADDRESS:-}  # Required - ROFLAdapter contract address
    
    restart: on-failure
    volumes:
      - /run/rofl-appd.sock:/run/rofl-appd.sock